dist: xenial
language: java
sudo: required
addons:
    apt:
        packages:
            - python3-setuptools
            - python3-pip
jdk:
    - openjdk8
    - openjdk9
    - openjdk10
    - openjdk11
    - openjdk12
script:
    - ./travis.sh
